name: Build master document
on:
  push:
    branches:
      - main
jobs:
  build_dict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup tools
        run: |
          sudo apt install -U nkf
      - name: Build
        run: |
          bash build.sh

      - name: Get current date and time for release
        env:
          TZ: "Asia/Tokyo"
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          body: |
            - Google IMEは`sohosai_GoogleIME.txt`
            - Windowsは`sohosai_Windows.txt`
            - macOSは`sohosai_macOS.txt`
            - ATOK(Windows)は`sohosai_ATOK-Windows.txt`
            - ATOK(macOS)は`sohosai_ATOK-macOS.txt`

            を用いてください
          files: |
            build/*
